---
# Install basic software
- name: Start message
  debug:
    msg: "Starting to install software"

#- include: roles/development/tasks/apt_installs.yml
- include: roles/development/tasks/other_installs.yml
 
- name: Finish message
  debug:
    msg: "Finished installng software"

