---
# Install basic software
- name: Start message for installing software from other sources  
  debug:
    msg: "Starting to install software from other sources"

- name: Prepare temporary directory for downloads and keys
  file:
    path: "{{ tmp_directory }}"
    state: directory
    mode: '0755'
  
- name: Download all sources ... does not seem to work for some odd reason
  get_url:
    url: "{{ item }}"
    dest: "{{ tmp_directory }}"
    mode: "0777"
  loop: "{{ urls }}"
      
- name: Finish message for installing software from other sources
  debug:
    msg: "Finished installng software from other sources"
