---
# Install basic software
- name: Start message for installing software from other sources
  debug:
    msg: "Starting to install software from other sources"

- name: Prepare temporary directory for downloads
  file:
    path: "{{ tmp_directory }}"
    state: directory
    mode: '0755'

- name: Download all sources
  get_url:
    url: "{{ item }}"
    dest: "{{ tmp_directory }}"
    mode: "0777"
  loop: "{{ urls }}"

- name: Install keys from url
  get_url:
    url: "{{ item.value.url }}"
    dest: "{{ item.value.dest }}"
  with_dict: "{{ apt_repo_keys }}"

- name: Install keys from keyservers
  apt_key:
    keyserver: "{{ item.value.keyserver }}"
    id: "{{ item.value.id }}"
    state: present
  with_dict: "{{ apt_repo_keyservers }}"

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ apt_repositories }}"

- name: Install downloaded debs
  apt:
    deb: "{{ tmp_directory }}/{{ item }}"
  loop: "{{ downloaded_debs }}"

- name: Finish message for installing software from other sources
  debug:
    msg: "Finished installng software from other sources"
