---
# variables needed for setting up development machine
tmp_directory: "/tmp/SETUP"

downloaded_debs:
  - gitkraken-amd64.deb
  - zoom_amd64.deb
# also doesn't work  - virtualbox-6.1_6.1.0-135406~Debian~buster_amd64.deb

apt_repo_keys:
  microsoft:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /usr/share/keyrings/vscode.gpg

  sil:
    url: https://packages.sil.org/keys/pso-keyring-2016.gpg
    dest: /etc/apt/trusted.gpg.d/pso-keyring-2016.gpg

  vagrant:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg

apt_repo_keyservers:
  monodevelop:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

apt_repositories:
  - "deb https://download.mono-project.com/repo/ubuntu stable-focal main"
  - "deb http://packages.sil.org/ubuntu jammy main"
# FIX?  - "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main" # fix?

packages:
  - audacity
  - bluefish
  - brasero
  - bridge-utils  # pre-req for Android Studio
  - build-essential
#      - chromium    # not available on Ubuntu 22.04
## failed  - code # requires some prior steps to set up repo
  - dia
  - geany
  - git
  - gimp
  - gnome-tweaks # automatically installed with Debian minimal ISO install
  - gpick
  - inkscape
  - lazarus
  - libreoffice
  - libvirt-clients   # pre-req for Android Studio
  - libvirt-daemon-system   # pre-req for Android Studio
#     - markdown
  - mono-complete
  - net-tools # for things like ifconfig
  - openjdk-11-jdk  # to be able to install Android studio
  - openssh-server
  - pandoc
  - playonlinux	# no need for complicated steps!
  - texlive
#  - virtualbox -> ouit of the box Ubuntu one is broken.
# failed user has to accept license  - virtualbox-ext-pack
# also some virtualbox dkms stuff needs installing ... see my script for that
  - vlc

urls:
  - https://github.com/unetbootin/unetbootin/releases/download/702/unetbootin-linux64-702.bin
  - https://zoom.us/client/5.12.6.173/zoom_amd64.deb
# problem with this URL?  - https://www.gitkraken.com/download/sa-linux-deb
  - https://release.gitkraken.com/linux/gitkraken-amd64.deb
# also broken (on my system) - https://download.virtualbox.org/virtualbox/6.1.0/virtualbox-6.1_6.1.0-135406~Debian~buster_amd64.deb
# Android studio: this version is "frozen" at or around 16-November-2022
  - https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.3.1.17/android-studio-2021.3.1.17-linux.tar.gz
# have to work out what to do with this android-studio download:
#  For ideas look at https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/how-to-install-android-studio-on-ubuntu-22-04.html
# 0) ? there may be some 32 bit libraries needed to be installed: libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
# 1) tar -zxvf android-studio-2021.3.1.17-linux.tar.gz
# 2) sudo mv android-studio /opt/
# 3) sudo ln -sf /opt/android-studio/bin/studio.sh /bin/android-studio